pipeline {
  agent any
  environment{
    IMAGE_TAG = "${BUILD_NUMBER}"
  }
  stages{
    stage('checkout'){
      steps{
        git branch: 'main', credentialsId: 'dockerhub', url: 'https://github.com/iam-imamhossain/Jenkins.git'
      }
    }
    stage('Build Docker'){
        steps{
            script{
               sh'''
                echo 'Build Docker image'
                cd Jenkins_docker_agent
                ls -ltr
                docker build -t imam2000/test:${BUILD_NUMBER} .    
                '''
            }
        }
    }
 stage('publish docker') {
    withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]) {
        // assumes Jib is configured to use the environment variables
        sh "docker build -t imam2000/test:${BUILD_NUMBER}"
    }
}
  }
}
