pipeline {
    agent {
        docker { image 'node:20.17.0-alpine3.20' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh '''
                ls -ltr
                touch with_docker.txt
                '''
            }
        }
        stage('with_out_docker'){
            steps{
                sh '''
                touch witout_docker.txt
                '''
            }
        }
    }
}
