pipeline {
  agent any
  environment{
    IMAGE_TAG = "${BUILD_NUMBER}"
  }
  stages{
    stage('checkout'){
      steps{
        git branch: 'main', credentialsId: 'dockerhub', url: 'https://github.com/iam-imamhossain/Jenkins.git'
      }
    }
    stage('Build Docker'){
        steps{
            script{
               sh'''
                echo 'Build Docker image'
                docker build -t imam2000/test:${BUILD_NUMBER} .    '''
            }
        }
    }
    stage('push the artifacts'){
        script{
            sh'''
            echo 'Push to Repo'
            docker push imam2000/test:${BUILD_NUMBER}   
            '''
        }
    }
  }
}
